name: YoutubePlus
main: me.Clarkcj.youtube.Youtube
version: mvn-version
authors: [Clarkcj, willies952002]

description: Tells The Players What the Server's YouTube/Twitch Channel is, also if someone is streaming/recording.
commands:
  youtube:
    description: Sends YouTube Channel Information
    aliases: yt
    usage: /<command> [link]
  stream:
    description: Sends Twitch Channel Information
    usage: /<command> [link]
    
permissions:
  ytp.*:
    description: Allows Access to Both ytp.r and ytp.s Permission Nodes
    default: op
    children:
      ytp.r: true
      ytp.s: true
  ytp.r:
    description: Allows a Player to Broadcast to The Server That They are Recording on YouTube
    default: op
  ytp.s:
    description: Allows a Player to Broadcast to The Server that They are Streaming on Twitch
    default: op
